### ISSUE TITLE
fail to install cond env

### ISSUE THREAD

**Issue by TomTom4** [weatherforce/weatherforce.github.io#5]
when following README.md instructions, the conda environment settings fails because it cannot find dependency **nbconvert=5.3.1=py_1**
a workaround was to suppress the =py_1
```bash
Solving environment: failed

ResolvePackageNotFound: 
  - nbconvert==5.3.1=py_1

```

**Comment by ghost** [comment]
Fixed by https://github.com/weatherforce/weatherforce.github.io/commit/63b22ac94a89b90f664cddb65603d956c0dd54f1
